### ISSUE TITLE
After October Release of Woocommerce Plugin throws fatal error

### ISSUE THREAD

**Issue by AdminWe3** [Prospress/woocommerce-subscriptions-recalculate-totals#1]
Hi
It may be coincidental but after the last Woocommerce update your very very useful plugin stopped working.  I've attached the error returned.  Note I have deleted the site name.

I haven't used the plugin for a while so it may be another conflict.  Although Woocommerce did make a break change in the early October release with how user roles are managed. (Thanks Woocommerce - NOT!).

Unfortunately I have had to change how sales tax is treated in Woocommerce and as we all know Woocommerce doesn't apply changes very well retrospectively!

Fatal error: Uncaught Error: [] operator not supported for strings in public_html/wp-content/plugins/woocommerce-subscriptions-recalculate-totals-master/woocommerce-subscriptions-manual-repair.php:117 Stack trace: #0 /public_html/wp-includes/class-wp-hook.php(286): wcs_recalculate_totals('') #1 public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 public_html/wp-settings.php(450): do_action('init') #4 public_html/wp-config.php(92): require_once('/home/...') #5 /public_html/wp-load.php(37): require_once('/home/...') #6 /home/public_html/wp-admin/admin.php(31): require_once('/home/...') #7 /home/public_html/wp-admin/index.php(10): require_once('/home/...') #8 {main} thrown in /home/public_html/wp-content/plugins/woocommerce-subscriptions-recalculate-totals-master/woocommerce-subscriptions-manual-repair.php on line 117

**Comment by AdminWe3** [comment]
Investigating further it seems it might be a problem with deprecation by PHP 7.1 and above concerning the way strings and arrays are treated.  It appears you have to explicitly declare an array and so [ ] doesn't work anymore.

**Comment by maximejobin** [comment]
I've forked the repo and made some fixes.

If interested:
https://github.com/SatelliteWP/woocommerce-subscriptions-recalculate-totals
